### ISSUE TITLE
Does Rey cache videos?

### ISSUE THREAD

**Issue by ryanpcmcquen** [s-kris/rey#4]
Because there is a video I really loved that was removed from YouTube, but I watched it a ton of times on Rey ...

**Comment by s-kris** [comment]
This is interesting. Rey doesn't cache videos. Can you share that video url?

**Comment by ryanpcmcquen** [comment]
https://youtu.be/3PoTRcLj_bM

**Comment by s-kris** [comment]
I'm sorry, I'm unable to play this video in Rey.

**Comment by ryanpcmcquen** [comment]
As I said, it was removed from YouTube.

**Comment by s-kris** [comment]
My bad, I misread it.
